name: Build and Push Docker Image

on:
  # push:
  #   branches: [ "master" ]
  release:
    types: published

env:
  IMAGE_NAME: paolooranges/quantconnect-lean-coinbasepro-tickers-downloader:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build --rm -t $IMAGE_NAME .
    - name: Push Docker Image
      run: docker push $IMAGE_NAME
