name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  release:
    types: published

env:
  IMAGE_NAME: paolooranges/quantconnect-lean-coinbasepro-tickers-downloader
  VERSION: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name == release}}
        tags: ${{ env.IMAGE_NAME }}/${{env.VERSION}}, ${{ env.IMAGE_NAME }}/latest
